### ISSUE TITLE
What characters does it remove?

### ISSUE THREAD

**Issue by tomek-he-him** [yoshuawuyts/whitespace-remove#1]
Things like `RegExp` treat `\n` as whitespace as well (https://en.wikipedia.org/wiki/Whitespace_character).

How about `\t`? Do you strip that as well? I can’t find any info in the docs or tests.

**Comment by yoshuawuyts** [comment]
right now all that happens is `val.replace(/( )/gm, '')`. PRs are welcome to make it remove more.

**Comment by tomek-he-him** [comment]
:+1: Thanks for making it explicit!
